---
- name: Prepare server for backuppc
  hosts: jump_server
  become: yes
  vars:
    created_username: backuppc

  tasks:
    - name: Create a new regular user with sudo privileges
      ansible.builtin.ansible.builtin.user:
        name: "{{ created_username }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        ansible.builtin.user: "{{ created_username }}"
        state: present
        key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"

    - name: Disable password authentication for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Disable password-based SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      ansible.builtin.service:
        name: ssh
        state: restarted
