---
- name: Install ArgoCD in kubernetes cluster
  hosts: jump_server
  tasks:
    - name: Create Argo CD namespace
      ansible.builtin.command: kubectl create namespace argocd
      ignore_errors: true

    - name: Install Argo CD using the official manifests
      ansible.builtin.command: |
        kubectl apply -n argocd -f \
          https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/{{ lookup('ansible.builtin.env', 'ARGOCD_VERSION')}}/manifests/ha/install.yaml

    - name: Patch the Argo CD server service to use LoadBalancer
      ansible.builtin.command: |
        kubectl patch svc argocd-server -n argocd -p '{"spec": { "type": "LoadBalancer" } }'
