---
- hosts: all
  name: Test
  become: true

  tasks:
    - name: Display if DISABLE_CLOUD_INIT is false
      ansible.builtin.debug:
        msg: "This message will be displayed if DISABLE_CLOUD_INIT is false"
      when: DISABLE_CLOUD_INIT == "false"

    - name: Display if DISABLE_CLOUD_INIT is true
      ansible.builtin.debug:
        msg: "This message will be displayed if DISABLE_CLOUD_INIT is true"
      when: DISABLE_CLOUD_INIT == "true"

