---
- hosts: jump_server

  tasks:
    - name: Ping server
      ansible.builtin.ping:

    - name: Basic usage
      ansible.builtin.debug:
        msg: " kubernetes version --{{ lookup('ansible.builtin.env', 'KUBERNETES_VERSION') }}--"
