---
- name: Bootstrap a gitlab group
  hosts: jump_server
  tasks:
    - name: Verify Flux CLI version
      ansible.builtin.command: flux --version
      register: flux_version_output
      changed_when: false

    - name: Display Flux CLI version
      ansible.builtin.debug:
        msg: "Flux version: {{ flux_version_output.stdout }}"

    - name: Run Flux pre-check for Kubernetes cluster
      ansible.builtin.command: flux check --pre
      register: flux_precheck_output
      changed_when: false

    - name: Display Flux pre-check output
      ansible.builtin.debug:
        msg: "{{ flux_precheck_output.stdout }}"
      failed_when: "'prerequisites checks passed' not in flux_precheck_output.stdout"

    - name: Check if Flux is already bootstrapped
      ansible.builtin.command: kubectl get deployment -n flux-system source-controller --ignore-not-found
      register: flux_bootstrap_check
      changed_when: false

    - name: Bootstrap Flux with default and extra components
      ansible.builtin.shell: |
        flux bootstrap gitlab \
          --token-auth=false \
          --ssh-hostname=gitlab.notyouraverage.dev \
          --read-write-key=true \
          --components source-controller,kustomize-controller,helm-controller,notification-controller \
          --components-extra image-reflector-controller,image-automation-controller \
          --cluster-domain cluster.internal \
          --url git@gitlab.notyouraverage.dev:YOUR-GROUP/YOUR-PROJECT.git \
          --branch main \
          --path ./clusters/my-cluster
      args:
        executable: /bin/bash
      changed_when: flux_bootstrap_check.stdout == ""

    - name: Check Flux installation
      ansible.builtin.command: flux check --pre
      changed_when: false
