---
- name: Setup Flux on Jump Server
  hosts: jump_server
  tasks:
    - name: Download Flux CLI installation script
      ansible.builtin.get_url:
        url: https://fluxcd.io/install.sh
        dest: /tmp/install_flux.sh
        mode: "0755"

    - name: Run Flux CLI installation script
      ansible.builtin.command: sudo bash /tmp/install_flux.sh
      args:
        creates: /usr/local/bin/flux

    - name: Verify Flux CLI version
      ansible.builtin.command: flux --version
      register: flux_version_output
      changed_when: false

    - name: Display Flux CLI version
      ansible.builtin.debug:
        msg: "Flux version: {{ flux_version_output.stdout }}"

    - name: Run Flux pre-check for Kubernetes cluster
      ansible.builtin.command: flux check --pre
      register: flux_precheck_output
      changed_when: false

    - name: Display Flux pre-check output
      ansible.builtin.debug:
        msg: "{{ flux_precheck_output.stderr }}"
      failed_when: "'prerequisites checks passed' not in flux_precheck_output.stderr"

    - name: Add Flux bash completion to profile
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: . <(flux completion bash)
        create: true
        mode: "0644"

    - name: Check if Flux is already bootstrapped
      ansible.builtin.command: kubectl get deployment -n flux-system source-controller --ignore-not-found
      register: flux_bootstrap_check
      changed_when: false

    - name: Bootstrap Flux with default and extra components
      ansible.builtin.shell: |
        flux bootstrap gitlab \
          --private \
          --token-auth=false \
          --read-write-key=true \
          --path clusters/zeus-k8s \
          --cluster-domain cluster.local \
          --owner={{ lookup('ansible.builtin.env', 'GITLAB_USERNAME') }} \
          --hostname={{ lookup('ansible.builtin.env', 'GITLAB_HOSTNAME') }} \
          --repository={{ lookup('ansible.builtin.env', 'GITLAB_USERNAME') }} \
          --ssh-hostname={{ lookup('ansible.builtin.env', 'GITLAB_SSH_HOSTNAME') }} \
          --components-extra image-reflector-controller,image-automation-controller \
          --components source-controller,kustomize-controller,helm-controller,notification-controller
      args:
        executable: /bin/bash
      changed_when: flux_bootstrap_check.stderr == ""
      environment:
        GITLAB_TOKEN: "{{ lookup('ansible.builtin.env', 'GITLAB_TOKEN') }}"

    - name: Check Flux installation
      ansible.builtin.command: flux check --pre
      changed_when: false
