---
- name: Register multiple GitLab Runners in Kubernetes
  hosts: jump_server
  tasks:
    - name: Ensure Helm is installed
      command: helm version
      ignore_errors: yes

    - name: Add GitLab Helm repository
      command: helm repo add gitlab https://charts.gitlab.io
      args:
        creates: ~/.cache/helm/repository/gitlab-index.yaml

    - name: Update GitLab Helm repository
      command: helm repo update gitlab

    - name: Generate values.yaml for GitLab Runner
      template:
        src: values.yaml.j2
        dest: /tmp/values.yaml

    - name: Install GitLab Runner with Helm
      command: >
        helm install \
          gitlab-runner -f /tmp/values.yaml \
          gitlab/gitlab-runner \
          --namespace kafka \
          --create-namespace

    - name: Verify runner installation
      command: kubectl get pods -n gitlab_runner
