---
- name: Install ZipKin
  hosts: jump_server
  tasks:
    - name: Add the Zipkin Helm repository
      ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
      args:
        creates: ~/.cache/helm/repository/bitnami-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      register: helm_repo_update_output

    - name: Install Zipkin in the default namespace
      ansible.builtin.shell: |
        helm install my-zipkin bitnami/zipkin \
          --set linkerd.injector.enabled=true \
          --version {{ lookup('ansible.builtin.env', 'ZIPKIN_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: THis needs to be removed

    - name: Verify Zipkin installation by checking pods
      ansible.builtin.command: kubectl  get pod
      register: zipkin_pods_output

    - name: Display running ZipKin pods
      ansible.builtin.debug:
        var: zipkin_pods_output.stdout
