- hosts: jump_server
  name: "Install ZipKin"

  tasks:
    - name: Add the Zipkin Helm repository
      shell: "helm repo add bitnami https://charts.bitnami.com/bitnami"
      args:
        creates: ~/.cache/helm/repository/bitnami-index.yaml

    - name: Update Helm repositories
      shell: "helm repo update"
      register: helm_repo_update_output

    - name: Install Zipkin in the default namespace
      shell: |
        helm install my-zipkin bitnami/zipkin \
          --set linkerd.injector.enabled=true \
          --version {{ lookup('ansible.builtin.env', 'ZIPKIN_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: THis needs to be removed

    - name: Verify Zipkin installation by checking pods
      shell: "kubectl  get pod"
      register: zipkin_pods_output

    - name: Display running ZipKin pods
      debug:
        var: zipkin_pods_output.stdout
