---
- name: Remove docker and docker compose from machines
  hosts: all
  become: true

  tasks:
    - name: Identify installed Docker packages
      ansible.builtin.command: dpkg -l | grep -i docker
      ignore_errors: true

    - name: Remove Docker packages if installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker-engine
        - docker
        - docker.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin

    - name: Remove Docker configuration and data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /etc/docker
        - /etc/apparmor.d/docker
        - /var/run/docker.sock
        - /var/lib/containerd
        - ~/.docker

    - name: Remove Docker group if it exists
      ansible.builtin.group:
        name: docker
        state: absent

    - name: Clean up unused dependencies
      ansible.builtin.apt:
        autoremove: true
        purge: true
