- hosts: jump_server
  name: "Install MySQL"

  tasks:
    - name: Add the Longhorn Helm repository
      shell: "helm repo add bitnami https://charts.bitnami.com/bitnami"
      args:
        creates: ~/.cache/helm/repository/bitnami-index.yaml

    - name: Update Helm repositories
      shell: "helm repo update"
      register: helm_repo_update_output

    - name: Install MySQL in the MySQL namespace
      shell: |
        helm install my-mysql bitnami/mysql \
          --set primary.persistence.enabled=true \
          --set primary.persistence.size=10Gi \
          --set primary.persistence.storageClass=longhorn-static \
          --set auth.rootPassword={{ lookup('ansible.builtin.env', 'MYSQL_ROOT_PASSWORD') }} \
          --set auth.database={{ lookup('ansible.builtin.env', 'MYSQL_AUTH_DATABASE') }} \
          --namespace mysql \
          --create-namespace \
          --set linkerd.injector.enabled=true \
          --version {{ lookup('ansible.builtin.env', 'MYSQL_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: THis needs to be removed

    - name: Verify MySQL installation by checking pods
      shell: "kubectl -n mysql get pod"
      register: mysql_pods_output

    - name: Display running MySQL pods
      debug:
        var: mysql_pods_output.stdout
