---
- name: Install MySQL
  hosts: jump_server
  tasks:
    - name: Add the Longhorn Helm repository
      ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
      args:
        creates: ~/.cache/helm/repository/bitnami-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      register: helm_repo_update_output

    - name: Install MySQL in the MySQL namespace
      ansible.builtin.shell: |
        helm install my-mysql bitnami/mysql \
          --set primary.persistence.enabled=true \
          --set primary.persistence.size=10Gi \
          --set primary.persistence.storageClass=longhorn-static \
          --set auth.rootPassword={{ lookup('ansible.builtin.env', 'MYSQL_ROOT_PASSWORD') }} \
          --set auth.database={{ lookup('ansible.builtin.env', 'MYSQL_AUTH_DATABASE') }} \
          --namespace mysql \
          --create-namespace \
          --set linkerd.injector.enabled=true \
          --version {{ lookup('ansible.builtin.env', 'MYSQL_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: THis needs to be removed

    - name: Verify MySQL installation by checking pods
      ansible.builtin.command: kubectl -n mysql get pod
      register: mysql_pods_output

    - name: Display running MySQL pods
      ansible.builtin.debug:
        var: mysql_pods_output.stdout
