---
- hosts: control_plane
  become: true
  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull

    - name: Initializing Kubernetes cluster
      shell: kubeadm init --apiserver-advertise-address=$(ip a |grep ens160|  grep 'inet ' | awk '{print $2}' | cut -f1 -d'/') --pod-network-cidr 10.244.0.0/16 --v=5
      register: myshell_output

    - debug: msg="{{ myshell_output.stdout }}"

    - name: Create .kube directory
      become: true
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin

    - name: Create Calico Operator using kubectl
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
      register: tigera_operator_output

    - name: Download Calico Custom Resources manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml

    - name: Apply Custom Resources manifest using kubectl
      ansible.builtin.command: kubectl apply -f /tmp/custom-resources.yaml
      register: calico_custom_resources_output

    - name: Ensure Tigera Operator was created successfully
      debug:
        msg: "{{ tigera_operator_output.stdout }}"

    - name: Ensure Calico Custom Resources applied successfully
      debug:
        msg: "{{ calico_custom_resources_output.stdout }}"
