---
- hosts: control_plane
  become: true

  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull

    - name: Download runc binary
      ansible.builtin.get_url:
        url: https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
        dest: /tmp/runc.amd64
        mode: '0755'

    - name: Install runc binary
      ansible.builtin.command:
        cmd: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

    - name: Download CNI plugins
      ansible.builtin.get_url:
        url: https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz
        dest: /tmp/cni-plugins-linux-amd64-v1.5.0.tgz

    - name: Create CNI bin directory
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        mode: '0755'

    - name: Extract CNI plugins
      ansible.builtin.unarchive:
        src: /tmp/cni-plugins-linux-amd64-v1.5.0.tgz
        dest: /opt/cni/bin
        remote_src: yes
        extra_opts: [ '--strip-components=1' ]

    - name: Configure crictl to use containerd
      ansible.builtin.command:
        cmd: crictl config runtime-endpoint unix:///var/run/containerd/containerd.sock

    - name: Initializing Kubernetes cluster
      shell: kubeadm init --apiserver-advertise-address=$(ip a |grep ens160|  grep 'inet ' | awk '{print $2}' | cut -f1 -d'/') --pod-network-cidr 10.244.0.0/16 --v=5
      register: myshell_output

    - debug: msg="{{ myshell_output.stdout }}"

    - name: Create .kube directory
      become: true
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin

    - name: Create Calico Operator using kubectl
      shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml --validate=false
      register: tigera_operator_output

    - name: Download Calico Custom Resources manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml

    - name: Change cidr value in the custom-resources.yaml
      ansible.builtin.replace:
        path: /tmp/custom-resources.yaml
        regexp: 'cidr: 192\.168\.0\.0/16'
        replace: 'cidr: 10.244.0.0/16'

    - name: Apply Custom Resources manifest using kubectl
      shell: kubectl apply -f /tmp/custom-resources.yaml
      register: calico_custom_resources_output

    - name: Ensure Tigera Operator was created successfully
      debug:
        msg: "{{ tigera_operator_output.stdout }}"

    - name: Ensure Calico Custom Resources applied successfully
      debug:
        msg: "{{ calico_custom_resources_output.stdout }}"
