---
- hosts: control_plane
  become: true

  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull

    - name: Download runc binary
      ansible.builtin.get_url:
        url: https://github.com/opencontainers/runc/releases/download/{{ lookup('ansible.builtin.env', 'RUNC_VERSION') }}/runc.amd64
        dest: /tmp/runc.amd64
        mode: '0755'

    - name: Install runc binary
      ansible.builtin.command:
        cmd: install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

    - name: Fetch and store node ip address
      ansible.builtin.set_fact:
        ip_address: "{{ hostvars[inventory_hostname]['ip_address'] }}"

    - name: Run kubeadm init with control plane endpoint
      shell: |
        kubeadm init \
        --apiserver-advertise-address={{ ip_address }} \
        --apiserver-cert-extra-sans=100.76.38.33 \
        --pod-network-cidr={{ lookup('ansible.builtin.env', 'POD_NETWORK_CIDR') }} \
        --control-plane-endpoint={{ ip_address }}:6443 \
        --v=5
      args:
        executable: /bin/bash
      register: myshell_output

    - debug: msg="{{ myshell_output.stdout }}"

    - name: Create .kube directory
      become: true
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin

- hosts: control_plane
  tasks:

    - name: Check if Kubernetes cluster is running
      command: kubectl cluster-info
      register: cluster_info
      ignore_errors: true

    - name: Print cluster status
      debug:
        var: cluster_info

    - name: Create Calico Operator using kubectl
      shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ lookup('ansible.builtin.env', 'CALICO_VERSION') }}/manifests/tigera-operator.yaml --validate=false
      register: tigera_operator_output

    - name: Download Calico Custom Resources manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/{{ lookup('ansible.builtin.env', 'CALICO_VERSION') }}/manifests/custom-resources.yaml
        dest: /tmp/custom-resources.yaml

    - name: Change cidr value in the custom-resources.yaml
      ansible.builtin.replace:
        path: /tmp/custom-resources.yaml
        regexp: 'cidr: 192\.168\.0\.0/16'
        replace: "cidr: {{ lookup('ansible.builtin.env', 'POD_NETWORK_CIDR') }}"

    - name: Apply Custom Resources manifest using kubectl
      shell: kubectl apply -f /tmp/custom-resources.yaml
      register: calico_custom_resources_output

    - name: Ensure Tigera Operator was created successfully
      debug:
        msg: "{{ tigera_operator_output.stdout }}"

    - name: Ensure Calico Custom Resources applied successfully
      debug:
        msg: "{{ calico_custom_resources_output.stdout }}"
