---
- hosts: control_plane
  become: true
  gather_facts: false
  tasks:

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command globally
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"
      delegate_to: localhost

    - name: Debug the join command
      debug:
        msg: "Join command: {{ join_command }}"


- hosts: workers
  become: true
  tasks:

    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Debug join command on workers
      debug:
        msg: "Worker node joining with command: {{ hostvars['localhost'].join_command }}"

    - name: Join the cluster using the global join command
      shell: "{{ hostvars['localhost'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt