---
- hosts: control_plane
  become: true
  gather_facts: false
  tasks:

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command globally
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      delegate_to: localhost



- hosts: workers
  become: true
  tasks:

    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Join the cluster
      shell: "{{ hostvars['localhost'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
