---
- hosts: control_plane
  become: true
  gather_facts: false
  tasks:

    - name: Get the token for joining the nodes with Kubernetes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout_lines }}"

    - name: Copy K8s Join command to file in master
      ansible.builtin.copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"

    - name: Copy join command from master to local ansible server
      fetch:
        src: "/tmp/kubernetes_join_command"
        dest: "/tmp/kubernetes_join_command"
        flat: yes


- hosts: workers
  become: true
  tasks:

    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Copy token to worker nodes.
      ansible.builtin.copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes with the master.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"

- hosts: control_plane
  tasks:
    - name: Label the newly joined worker nodes as workers using kubectl
      command: kubectl label node {{ item }} node-role.kubernetes.io/worker=worker
      loop: "{{ groups['workers'] }}"
