---
- hosts: control_plane
  become: true
  gather_facts: false
  tasks:

    - name: Get the token for joining the nodes with Kubernetes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout_lines }}"

    - name: Copy K8s Join command to file in master
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"

    - name: Copy join command from master to local ansible server
      fetch:
        src: "/tmp/kubernetes_join_command"
        dest: "/tmp/kubernetes_join_command"
        flat: yes


- hosts: workers
  become: true
  tasks:

    - name: Resetting kubeadm
      shell: kubeadm reset -f
      register: output

    - name: Copy token to worker nodes.
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes with the master.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"

#    - name: Label the node as a worker using kubectl
#      command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=
#      delegate_to: "{{ groups['control_plane'][0] }}"
#      when: joined_or_not is succeeded