---
- hosts: control_plane
  tasks:
    - name: Copy kube config file from control_plane to local Ansible server
      fetch:
        src: "/home/admin/.kube/config"
        dest: "/tmp/kube_config"
        flat: yes

- hosts: jump_server
  name: "Setup kube config in jump server"
  tasks:

    - name: Allow Kubernetes control plane ports in UFW
      become: true
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        comment: "{{ item.comment }}"
      with_items:
        - { port: 3000, proto: tcp, comment: "Semaphore UI Port" }

    - name: Create .kube directory
      become: true
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy the kube config to the jump server
      copy:
        src: /tmp/kube_config
        dest: $HOME/.kube/config
        mode: 0600

- hosts: jump_server
  name: "Install Helm"

  tasks:
    - name: Download the Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Run the Helm install script
      shell: ./get_helm.sh
      args:
        chdir: /tmp

    - name: Verify Helm installation
      shell: "helm version"
      register: helm_version_output
      changed_when: false
