---
- name: Get kubernetes config from control plane node
  hosts: control_plane
  tasks:
    - name: Copy kube config file from control_plane to local Ansible server
      fetch:
        src: /home/admin/.kube/config
        dest: /tmp/kube_config
        flat: true

- name: Install packages for network debugging
  hosts: jump_server
  tasks:
    - name: Update apt and install required system packages
      ansible.builtin.apt:
        pkg:
          - traceroute
          - nmap
          - fping
          - arp-scan
        state: latest
        update_cache: true

- name: Setup kube config in jump server
  hosts: jump_server
  tasks:
    - name: Allow Kubernetes control plane ports in UFW
      become: true
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        comment: "{{ item.comment }}"
      with_items:
        - { port: 3000, proto: tcp, comment: Semaphore UI Port }

    - name: Create .kube directory
      become: true
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: "0755"

    - name: Copy the kube config to the jump server
      ansible.builtin.copy:
        src: /tmp/kube_config
        dest: $HOME/.kube/config
        mode: "0600"

- hosts: jump_server
  name: Install Helm

  tasks:
    - name: Download the Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "0700"

    - name: Run the Helm install script
      shell: ./get_helm.sh
      args:
        chdir: /tmp

    - name: Verify Helm installation
      shell: helm version
      register: helm_version_output
      changed_when: false

- hosts: jump_server
  name: Install and setup Kubeseal
  vars:
    KUBESEAL_VERSION: "{{ lookup('ansible.builtin.env', 'KUBESEAL_VERSION') }}"

  tasks:
    - name: Download kubeseal
      ansible.builtin.get_url:
        url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ KUBESEAL_VERSION }}/kubeseal-{{ KUBESEAL_VERSION }}-linux-amd64.tar.gz"
        dest: "/tmp/kubeseal-{{ KUBESEAL_VERSION }}-linux-amd64.tar.gz"

    - name: Extract kubeseal binary only
      ansible.builtin.command:
        cmd: "tar -xvzf /tmp/kubeseal-{{ KUBESEAL_VERSION }}-linux-amd64.tar.gz kubeseal"

    - name: Install kubeseal binary
      ansible.builtin.command:
        cmd: "install -m 755 kubeseal /usr/local/bin/kubeseal"
      become: yes

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "/tmp/kubeseal-{{ KUBESEAL_VERSION }}-linux-amd64.tar.gz"
        state: absent
