---
- name: Get token to join cluster from control plane node
  hosts: control_plane
  become: true
  gather_facts: false
  tasks:
    - name: Get the token for joining the nodes with Kubernetes master.
      ansible.builtin.command: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: "Display node join command"
      ansible.builtin.debug:
        msg: "{{ kubernetes_join_command.stdout_lines }}"

    - name: Copy K8s Join command to file in master
      ansible.builtin.copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: /tmp/kubernetes_join_command

    - name: Copy join command from master to local ansible server
      ansible.builtin.fetch:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        flat: true

- name: Join new workers to kubernetes cluster
  hosts: new_workers
  become: true
  tasks:
    - name: Resetting kubeadm
      ansible.builtin.command: kubeadm reset -f
      register: output

    - name: Copy token to worker nodes.
      ansible.builtin.copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: "0777"

    - name: Join the Worker nodes with the master.
      ansible.builtin.command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - name: "Display node join command output"
      ansible.builtin.debug:
        msg: "{{ joined_or_not.stdout }}"

- name: Add worker label to add newly joined worker nodes
  hosts: control_plane
  tasks:
    - name: Label the newly joined worker nodes as workers using kubectl
      ansible.builtin.command: kubectl label node {{ item }} node-role.kubernetes.io/worker=worker
      loop: "{{ groups['workers'] }}"
