---
- name: Destroy the existing kubernetes cluster
  hosts: all:!jump_server
  become: true

  tasks:
    - name: Reset Kubernetes cluster (removes all nodes and config)
      ansible.builtin.command: kubeadm reset --force
      changed_when: false
      failed_when: false

    - name: Remove Kubernetes configuration directory
      become: true
      become_user: admin
      ansible.builtin.file:
        path: ~/.kube
        state: absent

    - name: Remove LInkerd configuration directory
      become: true
      become_user: admin
      ansible.builtin.file:
        path: ~/.linkerd2
        state: absent

    - name: Remove network interface configurations (CNI)
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent
      failed_when: false

    - name: Flush all iptables rules
      ansible.builtin.shell: set -o pipefail && iptables-save | grep -v KUBE | iptables-restore
      failed_when: false
      register: iptables_cleanup
      timeout: 10
      changed_when: false
      args:
        executable: /bin/bash

    - name: Clean up any additional containerd artifacts
      ansible.builtin.shell: |
        set -o pipefail
        ctr -n k8s.io container ls | awk '{print $1}' | xargs --no-run-if-empty ctr -n k8s.io container rm
        ctr -n k8s.io image ls | awk '{print $1}' | xargs --no-run-if-empty ctr -n k8s.io image rm
      failed_when: false
      changed_when: false
      args:
        executable: /bin/bash
