---
- name: Destroy the existing kubernetes cluster
  hosts: all
  become: true

  tasks:
    - name: Reset Kubernetes cluster (removes all nodes and config)
      ansible.builtin.command: kubeadm reset --force
      ignore_errors: true

    - name: Remove Kubernetes configuration directory
      become: true
      become_user: admin
      ansible.builtin.file:
        path: ~/.kube
        state: absent

    - name: Remove LInkerd configuration directory
      become: true
      become_user: admin
      ansible.builtin.file:
        path: ~/.linkerd2
        state: absent

    - name: Remove network interface configurations (CNI)
      ansible.builtin.command: rm -rf /etc/cni/net.d
      ignore_errors: true

    - name: Flush all iptables rules
      ansible.builtin.shell: |
        iptables-save | grep -v KUBE | iptables-restore
      ignore_errors: true
      register: iptables_cleanup
      timeout: 10

    - name: Clean up any additional containerd artifacts
      ansible.builtin.shell: |
        ctr -n k8s.io container ls | awk '{print $1}' | xargs --no-run-if-empty ctr -n k8s.io container rm
        ctr -n k8s.io image ls | awk '{print $1}' | xargs --no-run-if-empty ctr -n k8s.io image rm
      ignore_errors: true
