---
- name: Cleanup Kubernetes, reset iptables, and reload systemd
  hosts: all:!jump_server
  become: true

  tasks:
    - name: Reset Kubernetes cluster
      ansible.builtin.command: kubeadm reset --force
      changed_when: false
      failed_when: false

    - name: Purge Kubernetes packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        allow_change_held_packages: true
      loop:
        - kubeadm
        - kubectl
        - kubelet
        - kubernetes-cni
        - kube*

    - name: Remove Kubernetes configuration directory
      ansible.builtin.file:
        path: ~/.kube
        state: absent

    - name: Remove all specified directories and files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        recurse: true
      loop:
        - "{{ ansible_env.HOME }}/.kube"
        - /home/root/.kube
        - /etc/cni
        - /etc/kubernetes
        - /etc/apparmor.d/docker
        - /etc/systemd/system/etcd*
        - /var/lib/dockershim
        - /var/lib/etcd
        - /var/lib/kubelet
        - /var/lib/etcd2
        - /var/run/kubernetes
      failed_when: false

    - name: Clean up unused dependencies
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - name: Flush and delete iptables filter table
      ansible.builtin.command: iptables -F && iptables -X
      changed_when: false

    - name: Flush and delete iptables NAT table
      ansible.builtin.command: iptables -t nat -F && iptables -t nat -X
      changed_when: false

    - name: Flush and delete iptables raw table
      ansible.builtin.command: iptables -t raw -F && iptables -t raw -X
      changed_when: false

    - name: Flush and delete iptables mangle table
      ansible.builtin.command: iptables -t mangle -F && iptables -t mangle -X
      changed_when: false

    - name: Reload systemd manager to apply changes
      ansible.builtin.systemd:
        daemon_reload: true

- name: Remove containerd runtime
  hosts: all:!jump_server
  become: true

  tasks:
    - name: Remove containerd packages
      ansible.builtin.apt:
        name: containerd
        state: absent
        purge: true

    - name: Remove containerd directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/containerd
        - /var/lib/containerd
