---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-nfs-ephemeral
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-nfs-ephemeral
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-nfs-retained
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-nfs-retained
