- hosts: jump_server
  name: "Install Longhorn"

  tasks:

    - name: Add the Longhorn Helm repository
      shell: "helm repo add longhorn https://charts.longhorn.io"
      args:
        creates: ~/.cache/helm/repository/longhorn-index.yaml

    - name: Update Helm repositories
      shell: "helm repo update"
      register: helm_repo_update_output

    - name: Install Longhorn in the longhorn-system namespace
      shell: |
        helm install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --create-namespace \
          --version {{ lookup('ansible.builtin.env', 'LONGHORN_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: THis needs to be removed

    - name: Verify Longhorn installation by checking pods
      shell: "kubectl -n longhorn-system get pod"
      register: longhorn_pods_output

    - name: Display running Longhorn pods
      debug:
        var: longhorn_pods_output.stdout

#    - name: Create basic auth file
#      shell: |
#        echo "{{ lookup('ansible.builtin.env', 'LONGHORN_BASIC_AUTH_USER') }}:$(openssl passwd -stdin -apr1 <<< {{ lookup('ansible.builtin.env', 'LONGHORN_BASIC_AUTH_PASSWORD') }})" > /tmp/auth
#      args:
#        executable: /bin/bash
#
#    - name: Create Kubernetes secret for basic-auth
#      shell: kubectl -n longhorn-system create secret generic basic-auth --from-file=/tmp/auth
#
#    - name: Create Longhorn Ingress manifest
#      copy:
#        dest: /tmp/longhorn-ingress.yml
#        content: |
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          metadata:
#            name: longhorn-ingress
#            namespace: longhorn-system
#            annotations:
#              nginx.ingress.kubernetes.io/auth-type: basic
#              nginx.ingress.kubernetes.io/ssl-redirect: 'false'
#              nginx.ingress.kubernetes.io/auth-secret: basic-auth
#              nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
#              nginx.ingress.kubernetes.io/proxy-body-size: 10000m
#          spec:
#            rules:
#            - http:
#                paths:
#                - pathType: Prefix
#                  path: "/"
#                  backend:
#                    service:
#                      name: longhorn-frontend
#                      port:
#                        number: 80
#
#    - name: Apply Longhorn Ingress manifest
#      shell: kubectl -n longhorn-system apply -f /tmp/longhorn-ingress.yml
