---
- name: Install Linkerd CLI and Setup on Kubernetes Cluster
  hosts: jump_server
  tasks:
    - name: Download and install Linkerd CLI
      ansible.builtin.shell: |
        curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install-edge | sh
      args:
        creates: "{{ ansible_env.HOME }}/.linkerd2/bin/linkerd"
      environment:
        PATH: "{{ ansible_env.HOME }}/.linkerd2/bin:{{ ansible_env.PATH }}"

    - name: Add Linkerd CLI to PATH permanently
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: ^export PATH=.*linkerd2/bin
        line: export PATH=$HOME/.linkerd2/bin:$PATH
        state: present

    - name: Add Linkerd CLI to PATH for the current session
      ansible.builtin.shell: export PATH=$HOME/.linkerd2/bin:$PATH

    - name: Verify Linkerd CLI installation
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd version
      register: linkerd_version_output
      failed_when: "'Server version: unavailable' not in linkerd_version_output.stdout"

    - name: Check if Linkerd prerequisites are met in the Kubernetes cluster
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd check --pre
      register: linkerd_check_output
      failed_when: "'Status check results are' not in linkerd_check_output.stdout"

    - name: Install Linkerd CRDs
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd install --crds | kubectl apply -f -

    - name: Install Linkerd control plane
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd install | kubectl apply -f -

    - name: Wait for Linkerd installation to be ready
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd check
      register: linkerd_install_check_output
      failed_when: "'Status check results are' not in linkerd_install_check_output.stdout"

    - name: Install viz extension
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd viz install | kubectl apply -f -

    - name: Wait for Linkerd Viz installation to be ready
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd check
      register: linkerd_viz_install_check_output
      failed_when: "'Status check results are' not in linkerd_install_check_output.stdout"

    - name: Install jaeger extension
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd jaeger install --set webhook.collectorTraceProtocol=opentelemetry | kubectl apply -f

    - name: Wait for Jaeger installation to be ready
      ansible.builtin.shell: $HOME/.linkerd2/bin/linkerd jaeger check
      register: linkerd_jaeger_install_check_output
      failed_when: "'Status check results are' not in linkerd_install_check_output.stdout"
