---
- hosts: all
  vars:

  tasks:
    - name: Debug the applied labels
      debug:
        msg: "devices {{ ansible_devices }}"

    - name: Get the node role (master or worker)
      set_fact:
        node_role: "{{ 'master' if inventory_hostname in groups['control_plane'] else 'worker' }}"

    - name: Gather number of CPU cores
      set_fact:
        num_cores: "{{ ansible_processor_vcpus }}"

    - name: Gather total memory in MB
      set_fact:
        total_memory: "{{ ansible_memtotal_mb }}"

    - name: Debug the applied labels
      debug:
        msg: "Node {{ inventory_hostname }} labeled with: role={{ node_role }}, cpu={{ num_cores }}, ram={{ total_memory }}MB"

    - name: Basic usage
      ansible.builtin.debug:
        msg: " kubernetes version --{{ lookup('ansible.builtin.env', 'KUBERNETES_VERSION') }}--"
