---
- name: Install and setup tailscale
  hosts: jump_server
  become: yes
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('ansible.builtin.env', 'TAILSCALE_AUTH_KEY') }}"
        tailscale_state: "started"

  tasks:
    - name: Display the Tailscale IPv4 address
      debug:
        msg: "Tailscale IPv4 is: {{ tailscale_node_ipv4 }}"

    - name: Write Tailscale IPv4 to a file on the jump server
      delegate_to: "{{ jump_server }}"
      become: true
      become_user: admin
      ansible.builtin.copy:
        content: "{{ tailscale_node_ipv4 }}"
        dest: "~/tailscale_ipv4.txt"
      when: tailscale_node_ipv4 is defined
