---
- hosts: all
  vars:
    vars:
      disk_type: "{{ 'ssd' if ansible_devices['sda'].rotational == '0' else 'hdd' }}"

  tasks:
    - name: Get the node role (master or worker)
      set_fact:
        node_role: "{{ 'master' if inventory_hostname in groups['control_plane'] else 'worker' }}"

    - name: Gather number of CPU cores
      set_fact:
        num_cores: "{{ ansible_processor_vcpus }}"

    - name: Gather total memory in MB
      set_fact:
        total_memory: "{{ ansible_memtotal_mb }}"

    - name: Basic usage
      ansible.builtin.debug:
        msg: "hostname= {{ inventory_hostname }} Node Role: {{ node_role }} disk={{ disk_type }} cpu={{ num_cores }} ram={{ total_memory }}MB"

    - name: Basic usage
      ansible.builtin.debug:
        msg: " kubernetes version --{{ lookup('ansible.builtin.env', 'KUBERNETES_VERSION') }}--"
