---
- hosts: control_plane, workers, new_master
  vars:

  tasks:
    - name: Basic usage
      ansible.builtin.debug:
        msg: " kubernetes version --{{ lookup('ansible.builtin.env', 'KUBERNETES_VERSION') }}--"

