---
- name: Install UrBackup Client
  hosts: jump_server
  become: yes
  tasks:
    - name: Download UrBackup client installer
      get_url:
        url: "https://hndl.urbackup.org/Client/2.5.25/UrBackup%20Client%20Linux%202.5.25.sh"
        dest: "/tmp/urbackup_client.sh"
        mode: '0755'

    - name: Run UrBackup installer script
      command: "sh /tmp/urbackup_client.sh"
      args:
        removes: "/tmp/urbackup_client.sh"

    - name: Enable Internet mode for UrBackup client
      command: urbackupclientctl set-settings --authkey "35UnMoxTnJ" --name "jump-server" --server-url "urbackup://192.168.0.124:55414"

    - name: Ensure INTERNET_ONLY is true in /etc/default/urbackupclient
      lineinfile:
        path: /etc/default/urbackupclient
        regexp: 'INTERNET_ONLY=false'
        line: 'INTERNET_ONLY=true'
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Remove installer script
      file:
        path: "/tmp/urbackup_client.sh"
        state: absent

- name: Install dattobd for snapshots and incremental backups
  hosts: jump_server
  become: yes
  tasks:
    - name: Add Datto GPG key
      apt_key:
        url: "https://cpkg.datto.com/DATTO-PKGS-GPG-KEY"
        state: present

    - name: Add Datto repository to sources list
      apt_repository:
        repo: "deb [arch=amd64] https://cpkg.datto.com/datto-deb/public/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
        filename: "datto-linux-agent"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dattobd packages
      apt:
        name:
          - dattobd-dkms
          - dattobd-utils
        state: present