---
- name: Install Apache Kafka
  hosts: jump_server
  tasks:
    - name: Add the Kafka Helm repository
      ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
      args:
        creates: ~/.cache/helm/repository/bitnami-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      register: helm_repo_update_output

    - name: Install Kafka in the kafka namespace
      ansible.builtin.shell: |
        helm install my-kafka bitnami/kafka \
          --set externalAccess.enabled=true \
          --set externalAccess.service.type=LoadBalancer \
          --set externalAccess.autoDiscovery.enabled=true \
          --set linkerd.injector.enabled=true \
          --set metrics.jmx.enabled=true \
          --set replicaCount=2 \
          --set rbac.create=true \
          --set controller.automountServiceAccountToken=true \
          --set broker.automountServiceAccountToken=true \
          --namespace kafka \
          --create-namespace \
          --version {{ lookup('ansible.builtin.env', 'KAFKA_VERSION') }}
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true # TODO: This needs to be removed

    - name: Verify Kafka installation by checking pods
      ansible.builtin.command: kubectl -n mysql get pod
      register: mysql_pods_output

    - name: Display running MySQL pods
      ansible.builtin.debug:
        var: mysql_pods_output.stdout
