---
- name: Install KEDAs Auto Scaler
  hosts: jump_server
  tasks:
    - name: Add the KEDAs Helm repository
      ansible.builtin.command: helm repo add kedacore https://kedacore.github.io/charts
      args:
        creates: ~/.cache/helm/repository/kedacore-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      register: helm_repo_update_output

    - name: Install KEDAs in the keda namespace
      ansible.builtin.shell: |
        helm install keda kedacore/keda \
          --namespace keda \
          --create-namespace
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true

    - name: Verify Kedas installation by checking pods
      ansible.builtin.command: kubectl -n keda get pod
      register: keda_pods_output

    - name: Display running KEDA pods
      ansible.builtin.debug:
        var: keda_pods_output.stdout
