- hosts: jump_server
  name: "Install KEDAs Auto Scaler"

  tasks:
    - name: Add the Kafka Helm repository
      shell: "helm repo add kedacore https://kedacore.github.io/charts"
      args:
        creates: ~/.cache/helm/repository/kedacore-index.yaml

    - name: Update Helm repositories
      shell: "helm repo update"
      register: helm_repo_update_output

    - name: Install Kafka in the kafka namespace
      shell: |
        helm install keda kedacore/keda \
          --namespace keda \
          --create-namespace
      register: helm_install_output
      changed_when: "'release: installed' in helm_install_output.stdout"
      ignore_errors: true

    - name: Verify Kedas installation by checking pods
      shell: "kubectl -n keda get pod"
      register: keda_pods_output

    - name: Display running KEDA pods
      debug:
        var: keda_pods_output.stdout
