---
- name: Uninstall KEDA from Kubernetes cluster
  hosts: jump_server
  tasks:
    - name: Delete all ScaledObjects and ScaledJobs
      shell: |
        kubectl delete $(kubectl get scaledobjects.keda.sh,scaledjobs.keda.sh -A \
          -o jsonpath='{"-n "}{.items[*].metadata.namespace}{" "}{.items[*].kind}{"/"}{.items[*].metadata.name}{"\n"}')
      ignore_errors: yes
      register: keda_objects_deleted

    - name: Check if any KEDA ScaledObjects or ScaledJobs exist
      fail:
        msg: "Failed to delete all ScaledObjects and ScaledJobs."
      when: keda_objects_deleted.rc != 0

    - name: Uninstall KEDA Helm chart
      shell: helm uninstall keda -n keda
      ignore_errors: yes
      register: keda_uninstall

    - name: Check if KEDA Helm uninstall was successful
      fail:
        msg: "Failed to uninstall KEDA Helm release."
      when: keda_uninstall.rc != 0
