---
- name: Install containerd runtime
  hosts: all
  become: true

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Configure module for containerd.
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter
        create: true

    - name: Load the overlay module
      ansible.builtin.command: modprobe overlay

    - name: Load the br_netfilter module
      ansible.builtin.command: modprobe br_netfilter

    - name: Verify that the overlay module is loaded
      ansible.builtin.shell: lsmod | grep overlay
      register: overlay_module
      changed_when: false

    - name: Verify that the br_netfilter module is loaded
      ansible.builtin.shell: lsmod | grep br_netfilter
      register: br_netfilter_module
      changed_when: false

    - name: Print overlay module load status
      ansible.builtin.debug:
        msg: "Overlay module loaded: {{ overlay_module.stdout }}"

    - name: Print br_netfilter module load status
      ansible.builtin.debug:
        msg: "br_netfilter module loaded: {{ br_netfilter_module.stdout }}"

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Create the /etc/apt/keyrings directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker’s official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release
          }} stable
        filename: docker
        state: present
        update_cache: true

    - name: Update cache & Full system update
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true

    - name: Install containerd
      ansible.builtin.apt:
        name:
          - containerd
        state: present

    - name: Configure containerd.
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Generate the default containerd configuration
      ansible.builtin.shell: |
        containerd config default | tee /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Update SystemdCgroup to true in containerd config
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: ^(\s*SystemdCgroup\s*=\s*)false
        line: "            SystemdCgroup = true"
        backup: true

    - name: Enable and start containerd service
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: restarted
        daemon-reload: true

    - name: Verify containerd service is running
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true
