---
- name: Remove containerd runtime
  hosts: all
  become: true

  tasks:
    - name: Remove containerd packages
      ansible.builtin.apt:
        name: containerd
        state: absent
        purge: true

    - name: Remove containerd directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/containerd
        - /var/lib/containerd
