---
- hosts: all
  become: true

  tasks:

    - name: Remove containerd packages
      apt:
        name: containerd
        state: absent
        purge: yes

    - name: Remove containerd directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/containerd
        - /var/lib/containerd
