---
- hosts: jump_server
  name: Install and setup MetalLB LoadBalancer
  tasks:
    - name: Disable Strict ARP for the cluster
      ansible.builtin.shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl apply -f - -n kube-system"
      register: res
      changed_when: res.rc != 0

    - name: Ensure /tmp/metallb directory exists
      ansible.builtin.file:
        path: /tmp/metallb
        state: directory
        mode: "0755"

    - name: Create metallb ip address pool
      ansible.builtin.copy:
        dest: /tmp/metallb/metallb-addr-pool.yml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: addr-pool
            namespace: metallb-system
          spec:
            addresses:
              - {{ lookup('ansible.builtin.env', 'METALLB_IP_ADDRESSES') }}
        mode: "0644"

    - name: Create metallb L2 advertise config
      ansible.builtin.copy:
        dest: /tmp/metallb/metallb-advertise.yml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2adv
            namespace: metallb-system
        mode: "0644"

    - name: Install MetalLB
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ lookup('ansible.builtin.env', 'METALLB_VERSION') }}/config/manifests/metallb-native.yaml
      register: res
      changed_when: res.rc != 0

    - name: Wait for MetalLB pods to be ready
      ansible.builtin.shell: |
        kubectl wait --namespace metallb-system \
          --for=condition=ready pod \
          --selector=app=metallb \
          --timeout=300s
      register: res
      changed_when: "false"

    - name: Apply the metallb ip address pool configuration
      ansible.builtin.command: kubectl apply -f /tmp/metallb/metallb-addr-pool.yml
      register: res
      changed_when: res.rc != 0

    - name: Apply the metallb advertise configuration
      ansible.builtin.command: kubectl apply -f /tmp/metallb/metallb-advertise.yml
      register: res
      changed_when: res.rc != 0
